apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:  # Corrected 'lables' to 'labels'
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:  # Corrected 'matchLables' to 'matchLabels'
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: myproj
        image: vishalsd/project2
        ports:
        - containerPort: 80
